### ISSUE TITLE
Add editor icons to guides

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#10048]
Add editor toolbar icons to user guides.

Guides that could use toolbar icons:

*   [x] basic text styles (plenty)
*   [x] block indentation
*   [x] block quote
*   [x] code blocks
*   [x] export to PDF
*   [x] export to Word
*   [x] find and replace
*   [x] font (plenty)
*   [x] highlight
*   [x] HR
*   [x] HTML embed
*   [x] link
*   [x] lists (both guides)
*   [x] math / chem formulas
*   [x] media embed
*   [x] page break
*   [x] pagination
*   [x] remove formatting
*   [x] restricted editing
*   [x] revision history
*   [x] select all
*   [x] special characters
*   [x] spelling and grammar checking
*   [x] tables (goddamn plenty of those little pesky bastards)
*   [x] text alignment

Collaboration features:

*   [x] comments
*   [x] track changes

Post-release new guides:

*   [x] images (plenty of those, really plenty)
*   [x] source editing

**Comment by godai78** [comment]
That's it for now, more after code release.
