### ISSUE TITLE
Various CKE5 documentation upgrades

### ISSUE THREAD

**Issue by godai78** [ckeditor/ckeditor5#10681]
## 📝 Provide a description of requested docs changes

Follow up from: cksource/docs#368

Scope: update and modernize the docs system as a whole. Base the docs' flow on user stories and rearrange guides, sections, and elements accordingly. Add helpers and easier ways to reach the guides needed.

Refresh the docs interface, make it lighter, more informative, and easier to follow.

Find what is missing and fill in the blanks, update what was forgotten, interconnect cases and issues.

Provide more exposition for selected areas and products.

Steps:

*   [x] redesign the "builds" section #10647
*   [x] rewrite the CKE5 Installation landing page to explain needs and user paths
    *   [x] create a quick-start user quiz to easier choose the proper guide for first-timers cksource/ckeditor5-internal#1065
    *   [x] new quick-start guide cksource/ckeditor5-internal#1262
    *   [x] mention Online Builder #10824
        *   [x] preferably add a guide, too cksource/ckeditor5-internal#1270
*   [x] arrange the install docs in a more useful manner cksource/ckeditor5-internal#1069
*   [x] redesign main landing page (push down CKE4, drop Letters to Other etc.) cksource/docs#402
*   [ ] clean up the sidebar from abundant elements cksource/ckeditor5-internal#1081
*   [ ] expose collaboration features
*   [x] update CKE4 to CKE5 migration guide #11128
*   [ ] add permalink dropdown for older docs versions #10613

Ideas welcome. Let's make it epic.
