### ISSUE TITLE
Migrate CKEditor 5 to TypeScript - follow-ups

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#12027]
This issue serves as an umbrella for all the tasks that need to be done after migrating the project to TypeScript, including bug fixes, code refactoring, and feature enhancements.

Additionally, this issue is also a platform for the community to share their feedback and suggestions regarding the TypeScript migration.

## Tasks
- [x] https://github.com/ckeditor/ckeditor5/issues/13831
- [x] https://github.com/ckeditor/ckeditor5/issues/13743
- [ ] https://github.com/ckeditor/ckeditor5/issues/11723
- [x] https://github.com/ckeditor/ckeditor5/issues/11888
- [x] https://github.com/ckeditor/ckeditor5/issues/13434
- [x] https://github.com/ckeditor/ckeditor5/issues/13855
- [x] https://github.com/ckeditor/ckeditor5/issues/13830
- [x] https://github.com/ckeditor/ckeditor5/issues/13750
- [x] https://github.com/ckeditor/ckeditor5/issues/12853
- [x] https://github.com/ckeditor/ckeditor5/issues/12720
- [x] https://github.com/ckeditor/ckeditor5/issues/12763
- [x] https://github.com/ckeditor/ckeditor5/issues/12218

## Community Feedback

We encourage the community to share their feedback and suggestions regarding the TypeScript migration. If you encounter any bugs or issues related to the migration, please report them here. We value your feedback and will use it to improve the quality of the project. Thank you for your support and contribution.

**Comment by mmichaelis** [comment]
## Replace "export type" by "export" in index.ts

We are just at upgrading to CKEditor 37.x, thankfully being able to incorporate your TypeScript typings!

We stumbled across some "export type", though, in `index.ts`, where we require a full export. From discussion, our perception is, that `index.ts` is the "declared public API" and direct imports like from `imageinline` should be prevented – but are the only workaround for us now.

We would require the following to be full exports instead:

https://github.com/ckeditor/ckeditor5/blob/629f8ab55d75516eb8151cfc250952667d4427e6/packages/ckeditor5-image/src/index.ts#L37

https://github.com/ckeditor/ckeditor5/blob/629f8ab55d75516eb8151cfc250952667d4427e6/packages/ckeditor5-image/src/index.ts#L39

https://github.com/ckeditor/ckeditor5/blob/629f8ab55d75516eb8151cfc250952667d4427e6/packages/ckeditor5-image/src/index.ts#L40

We may provide details, why we need these. For `ImageInline`, for example, we do not support `ImageBlock`, so that we directly need to reference `ImageInline` instead of the aggregator `Image`.

## Add to index.ts

And the following, we would like to be exported in the corresponding `index.ts`:

https://github.com/ckeditor/ckeditor5/blob/629f8ab55d75516eb8151cfc250952667d4427e6/packages/ckeditor5-core/src/commandcollection.ts#L16

https://github.com/ckeditor/ckeditor5/blob/629f8ab55d75516eb8151cfc250952667d4427e6/packages/ckeditor5-link/src/ui/linkactionsview.ts#L27

https://github.com/ckeditor/ckeditor5/blob/629f8ab55d75516eb8151cfc250952667d4427e6/packages/ckeditor5-link/src/ui/linkformview.ts#L42

https://github.com/ckeditor/ckeditor5/blob/629f8ab55d75516eb8151cfc250952667d4427e6/packages/ckeditor5-editor-classic/src/classiceditoruiview.ts#L20

Same as above, we may provide details, why we require them, so that we may discuss alternative paths we could take.

## For Reference: Our Usages

We added a comment to our upgrade PR to reference issues reported here: https://github.com/CoreMedia/ckeditor-plugins/pull/145 (e.g., https://github.com/CoreMedia/ckeditor-plugins/pull/145/commits/55200cbf8f8567e0d24df4a021d0d0318c09ee91).

Similar to:

```typescript
// See ckeditor/ckeditor5#12027.
```

So, you may see, for example, that we only require `CommandCollection` on integration test level. Thus, it may be completely valid to state, that it should not go into `index.ts` just for this purpose.

**Comment by Witoso** [comment]
@mmichaelis we appreciate the feedback! We will review it here: #13864

**Comment by mmichaelis** [comment]
Just created another issue in this context:

* #13904

**Comment by Inviz** [comment]
Cant find a way to import ViewTreeWalker from engine.

**Comment by Inviz** [comment]
Also please add inferred types for event listeners. It's backwards now, type has to be provided and that validates the event name.

**Comment by arkflpc** [comment]
Hi @Inviz ,

I've created a ticket to provide `ViewTreeWalker` (#14158).

Regarding the events: You can import `ViewDocumentCopyEvent` from ckeditor5-clipboard. I.e.

```typescript
import { ViewDocumentCopyEvent } from '@ckeditor/ckeditor5-clipboard'
```

We tried to provide automatic type inference for event listeners, like [lib.dom.d.ts](https://github.com/TypeStrong/tscs/blob/master/lib/node_modules/TypeScript/bin/lib.dom.d.ts) do. However, it turned out to be very difficult with the event system we have in `ckeditor5`. The option to refactor events was out-of-scope, because almost everything relies on this. If you are interested in solutions we tried, please read [this comment](https://github.com/ckeditor/ckeditor5/issues/12076#issuecomment-1191344179).

**Comment by CKEditorBot** [comment]
There has been no activity on this issue for the past year. We've marked it as stale and will close it in 30 days. We understand it may still be relevant, so if you're interested in the solution, leave a comment or reaction under this issue.

**Comment by CKEditorBot** [comment]
We've closed your issue due to inactivity. We understand that the issue may still be relevant. If so, feel free to open a new one (and link this issue to it).
