### ISSUE TITLE
Drag and Drop of blocks

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#13933]
Currently, CKEditor 5 allows dragging textual content and objects (like images or tables). Such content can be then dropped at any possible caret position. It allows the rearranging of parts of the content without cutting and pasting them. It’s a feature implemented by all rich text editors for decades.

However, the “inline” mode of this feature does not enable the user to quickly and efficiently rearrange content blocks (e.g. paragraphs, headings, list items, images, or tables). Therefore, modern content authoring tools such as Notion popularized a block-based drag-and-drop functionality. In such implementations, entire content blocks can be easily grabbed and moved up/down in the document.

We plan to introduce a block-based drag-and-drop functionality to CKEditor 5 to boost content creators’ productivity and “modernize” the UX of the editor.

### Experiment 
- [x] #14033

### Stabilizing

The stabilization efforts will consist of bug fixing as well as adding a few new behaviors if the time frame allows.

#### Bug fixing
- [x] https://github.com/ckeditor/ckeditor5/issues/14968
- [x] https://github.com/ckeditor/ckeditor5/issues/14740
- [x] https://github.com/ckeditor/ckeditor5/issues/14710
- [x] https://github.com/ckeditor/ckeditor5/issues/14640
- [ ] https://github.com/ckeditor/ckeditor5/issues/11130
- [ ] https://github.com/ckeditor/ckeditor5/issues/14709
- [x] https://github.com/ckeditor/ckeditor5/issues/15029

#### New behaviors
- [x] https://github.com/ckeditor/ckeditor5/issues/14645
- [x] https://github.com/ckeditor/ckeditor5/issues/14744
- [x] https://github.com/ckeditor/ckeditor5/issues/14646
- [x] https://github.com/ckeditor/ckeditor5/issues/14969

#### Enablement
- [x] https://github.com/ckeditor/ckeditor5/issues/14734
- [x] https://github.com/ckeditor/ckeditor5/issues/14831

### Community feedback
- [ ] #2664
- [ ] #11737
- [ ] #12894

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Further enhancements extracted to the #15110.
