### ISSUE TITLE
🖼️ [Feedback needed] Supporting image height attribute

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14146]
# Image feature compatibility with CKEditor 4 (height)

**[UPDATE]**

### Please test things out if you can, the more feedback and eyeballs we get, the more confident we will be that the implementation is correct.

The changes can be tested on the `ck/epic/14146-support-image-height-attribute` branch. A special manual test was created to reflect different scenarios, [`imagesizeattributesallcases.html`](http://localhost:8125/ckeditor5-image/tests/manual/imagesizeattributesallcases.html) (launched by the `yarn manual -sw -f 'image'`).

[The details of the changes are described in the comment below.
](https://github.com/ckeditor/ckeditor5/issues/14146#issuecomment-1632607316)

## Main problem statements

When implementing images it looks like there are still some areas in which CKEditor 5 lags behind the CKE4. This applies only to inline images because CKEditor 4’s `image` plugin could only generate inline images. We don’t have to care about the behavior of `image2` (low popularity).

After initial research, it looks like the main missing attribute is height, and the following problems need to be solved.

1. How to preserve the image’s height and width with **the content that is already out there** and is loaded to the editor.
2. Should **we eagerly set image height and width** as it will produce better rendering? What about:
    1. the resizing implementation?
    2. should we set those values proactively when uploading of the image happens?

## Feedback and Community

- This is very important for modern browsers as height and width [prevent layout shifts and improve the experience of your site visitors.](https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/)
- We have reports from Drupal about missing `height` and its relation to image resizing.
    - [https://www.drupal.org/project/drupal/issues/3336446#comment-14888366](https://www.drupal.org/project/drupal/issues/3336446#comment-14888366)
    - [https://www.drupal.org/project/drupal/issues/3321296](https://www.drupal.org/project/drupal/issues/3321296)
    - When the image is resized in CKEditor 4, both `height` and `width` attributes are added. The attributes persist if the text format is upgraded to use CKEditor 5.
- https://github.com/ckeditor/ckeditor5/issues/5154
- https://github.com/ckeditor/ckeditor5/issues/10838
- https://github.com/ckeditor/ckeditor5/issues/11393

### FYI

The `srcset` attribute specifies the image variants dedicated for the various screen sizes for the web browser to choose from (360px, 720px, 1080px, 1440px, etc.). For instance, the `image.jpg` file uploaded by the user will have the following markup:

`sizes`One or more strings separated by commas, indicating a set of source sizes. Each source size consists of:
1. A [media condition](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax). This must be omitted for the last item in the list.
2. A source size value.
Media Conditions describe properties of the *viewport*, not of the *image*. For example, `(max-height: 500px) 1000px` proposes to use a source of 1000px width, if the *viewport* is not higher than 500px.

If the `srcset` attribute uses width descriptors, the `sizes` attribute must also be present, or the `srcset` itself will be ignored.

CKEditor5 when **using responsive image** (EasyImage) the `width` attribute is set but not the `height`. CKBox is not doing it.

Good explanation of the impact to `width` and `height` on CLS: [https://www.aleksandrhovhannisyan.com/blog/setting-width-and-height-on-images/](https://www.aleksandrhovhannisyan.com/blog/setting-width-and-height-on-images/)

> Essentially, the width and height attributes are meant for **initializing an image’s aspect ratio**, not for dictating the width and height at which it renders—that’s the job of CSS. Once an image has loaded in, if you want to apply some custom CSS to size it differently, you can do so without changing the image’s intrinsic aspect ratio sizing.

## Use cases

Problem 1: I have HTML with `width` and `height` set and it doesn't load to the editor.
Outcome: Load the width and height attributes of the image, e.g. setData content to the model (no GHS).

---

Problem 2: When I resized an image (with `width` and `height`), and I have the resized image placed on the page there should not be a layout shift. Also, I still want to resize with **the aspect ratio locked**.
Outcome: `width` and `height` stay but the image is resized with the aspect ratio intact.

---

Problem 3: When I insert images, I want `width` and `height` set automatically.
Outcome: After upload those attributes appear on the image element.

## Scope

* [x] https://github.com/ckeditor/ckeditor5/issues/14147
* [x] https://github.com/ckeditor/ckeditor5/issues/14313
* [x] #14201 (solving problems 1 and 2)
* [x] #14202 (solving problem 3)
* [x] https://github.com/ckeditor/ckeditor5/issues/14357
* [x] https://github.com/ckeditor/ckeditor5/issues/14366
* [x] https://github.com/ckeditor/ckeditor5/issues/14542
* [x] https://github.com/ckeditor/ckeditor5/issues/14532
* [x] https://github.com/ckeditor/ckeditor5/issues/14557
* [x] https://github.com/ckeditor/ckeditor5/issues/14531

## Out of scope

Problem 4: As a user, I want to change the `width` and `height` attributes.
Outcome: `width` and `height` attributes are configurable on the UI.

Decided to keep it out of scope for now. `width` and `height` should set the [intrinsic size of the image](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#supported_image_formats) to lock the aspect ratio for the browser, and restyling of images should be done via the CSS.

**Comment by Witoso** [comment]
Questions:
* if there's only a `height` set should we accept it?
* `height: auto` collides with a set height in the content.
* should there be a config option that turns it off?

**Comment by Witoso** [comment]
We decided that we will set those attributes on upload by default as the most content-friendly option.

However, research needs to be conducted on how the proposed solution will behave in a variety of content sources. This initiative is a hit or miss as we cannot roll back easily. CKEditor 4 output data, and Drupal's content, as well as users' intent preservation, need to be taken into account. One of the challenges is resizing in CKE4 by tweaking the aspect ratio of the original image.

Tracking in: https://github.com/ckeditor/ckeditor5/issues/14313

**Comment by wimleers** [comment]
> In CKE4, it was possible to tweak the aspect-ratio of an image. We decided to support this in the editor, and if the aspect-ratio was changed, we should show it as changed.

IIRC we had previously concluded that this was very rarely used? Am I now misremembering that? 🤔 Asking because this this complicates the implementation enormously.
Checking … found it: [the `image2` demo](https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html) clearly shows that there's no ability to customize the aspect ratio?

**Comment by Witoso** [comment]
Unfortunately, it may be a rare case the case in Drupal which, I think, didn't implement the modal. In the plain CKE4, double-click on an image showed the dimensions, with a pretty obvious mechanism to unlock the aspect ratio.

![](https://github.com/ckeditor/ckeditor5/assets/9881379/831a099b-0318-4951-b429-79a66f6257d1)

**Comment by Witoso** [comment]
This feature hit the `master` and is available on [nightly releases](https://github.com/ckeditor/ckeditor5/issues/14724) and [nightly docs](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html) to test.

**Comment by KlemenDEV** [comment]
Nice, thank you!

**Comment by Witoso** [comment]
Setting the width/height via the UI: https://github.com/ckeditor/ckeditor5/issues/15044.
