### ISSUE TITLE
Integrator's API improvements

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#14431]
We lack a middle ground between adding features and adding a plugin in terms of integrators. Integrators are users that want to interact with the editor's API with JS, but don't want to write a plugin and touch the advanced framework parts. This was observed when listening to the community (on GH/Drupal).

**Subproblem 1** 

Simple editor API interactions are not visible in our docs. We don’t have a quick glance and intro on basic js interactions with the editor. Useful commands and methods are scattered between plugins, so it’s hard for the newcomer to find them. We don’t advertise `function(editor) {}`  plugin enough.

We want to provide better guidance in the following areas:
* Access to the editor's API and adding simple plugins.
* Insertion of content.
* Selection & Focus & Caret.
* Deletion.
* Finding elements.
* Adding a simple toolbar button.
* Basic events.

********Outcome********

A doc page that shows the most common scenarios and introduces a user to the high-level API. (interactions, commands, events).

**************************Subproblem 2 - TBD**************************

It may turn out that some “simple” things are not that simple or are impossible. We would need to make a decision to introduce some new elements to the API.

**Scope**
- [x] Check what CKEditor 4 allowed.
- [x] Gather code examples
- [x] Documentation  proposal.
- [x] Discuss docs structure.
- [x] Finalize the doc and publish it.

Along the way, we will gather areas that don't provide good interface.

**Comment by Witoso** [comment]
A few interesting points on the CKE4 API.

Adding an item to a toolbar looks much easier and less with code:

```javascript
editor.ui.addButton( 'Timestamp', {
    label: 'Insert Timestamp',
    command: 'insertTimestamp',
    toolbar: 'insert'
});
```

As well as plugins:

```javascript
CKEDITOR.plugins.add( 'timestamp', {
    icons: 'timestamp',
    init: function( editor ) {
        //Plugin logic goes here.
    }
});
```

Declaring widgets - everything in one object (button, icon, etc.).

```javascript
CKEDITOR.plugins.add( 'simplebox', {
    requires: 'widget',
    button: 'Create a simple box',


    icons: 'simplebox',

    init: function( editor ) {
      editor.widgets.add( 'simplebox', {
        // Widget code.
    } );
    }
} );
```

And there's a possibility to add a plugin in the runtime.

```javascript
    CKEDITOR.replace( 'editor1', {
        // Load the Simple Box plugin.
        extraPlugins: 'simplebox'
    } );
```

Obviously, CKE4 didn't have an abstracted model layer so discussing differences here doesn't make sense.

Important to mention that the interaction with CKE4 is quite easily possible on the frontend without requiring additional imports. Everything is available through the `CKEDITOR` entry point. In CKE5 you need additional packages for some extensions (e.g. `ButtonView`, `Widget`).

The most eye-opening thing is the comparison of the simple box plugin done in CKE4 and CKE5.  CKE4: ~40 lines of code. CKE5: ~200 LOCs. And while we understand where this difference comes from (schema, the model, extra safety, etc.), it's still a fact that the CKE5 plugins will be longer. The more we can improve this experience, the better.

**Comment by Witoso** [comment]
New docs on production!
