### ISSUE TITLE
Further enhancements to the drag & drop: list subitems support / scrolling.

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5#15110]
## 📝 Provide a description of the improvement

After implementing the block drag & drop, we still have ideas how to improve it.

### New behaviors

- [ ] https://github.com/ckeditor/ckeditor5/issues/14647
- [ ] https://github.com/ckeditor/ckeditor5/issues/14766
- [x] https://github.com/ckeditor/ckeditor5/issues/14737
- [ ] https://github.com/ckeditor/ckeditor5/issues/14940
- [x] https://github.com/ckeditor/ckeditor5/issues/15058

### Tweaks and bug fixing

- [x] https://github.com/ckeditor/ckeditor5/issues/14739
- [x] https://github.com/ckeditor/ckeditor5/issues/14738
- [x] https://github.com/ckeditor/ckeditor5/issues/14711
- [x] https://github.com/ckeditor/ckeditor5/issues/14712
- [x] https://github.com/ckeditor/ckeditor5/issues/14950
- [x] https://github.com/ckeditor/ckeditor5/issues/14643
- [x] https://github.com/ckeditor/ckeditor5/issues/14641
- [x] https://github.com/ckeditor/ckeditor5/issues/14735

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by CKEditorBot** [comment]
There has been no activity on this issue for the past year. We've marked it as stale and will close it in 30 days. We understand it may still be relevant, so if you're interested in the solution, leave a comment or reaction under this issue.

**Comment by CKEditorBot** [comment]
We've closed your issue due to inactivity. We understand that the issue may still be relevant. If so, feel free to open a new one (and link this issue to it).
