### ISSUE TITLE
[Umbrella] Undo/redo issues

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#2723]
Since we know that there a lot of issues with undo found after the recent refactoring let's report them in one place.

* [ ] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313443657
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313444518
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313444977
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313446087
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313446928
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313619534
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-314216007
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-315124980
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-315731182
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-321190168
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-322716083
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-322998652
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-323011139
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-323682195
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-328790495
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-333163151
* [ ] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-335743590
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-335756219
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-335812474
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336398944
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336415007
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336424282
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336439220
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336450743
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336468200
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336810386
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336869808
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-336889100
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-337151475
* [ ] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-339969647
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-340709013
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-340720087
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-355947865
* [x] https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-355959457  
* [x] https://github.com/ckeditor/ckeditor5/issues/2723#issuecomment-366633196

**Comment by CKEditorBot** [comment]
There has been no activity on this issue for the past year. We've marked it as stale and will close it in 30 days. We understand it may be relevant, so if you're interested in the solution, leave a comment or reaction under this issue.

**Comment by CKEditorBot** [comment]
We've closed your issue due to inactivity over the last year. We understand that the issue may still be relevant. If so, feel free to open a new one (and link this issue to it).
