### ISSUE TITLE
Support for styling table & table cells

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#3287]
We can add support for styling table cells.

In this case it doesn't seem reasonable to approach the problem with our usual "closed set of styles" (like image "full" and "aside" styles). Instead, we need a full flavored option.

One way to imagine it would be a button "cell properties" in a table toolbar. It would open a bigger panel where you could choose border style, border width, cell size, alignment (v and h), background color, border color.

---

If you'd like to see this feature implemented, please react with 👍 to this ticket.

**Comment by jodator** [comment]
Just to confirm - the table/tableCell/tableRow properties should be prefixed with model element name?
- Model names for attributes on `tableCell`:
    - `tableCellBorderWidth`, `tableCellBorderColor`, `tableCellBorderStyle`,
    - `tableCellBackgroundColor`
    - `tableCellPadding`
    - `tableCellVerticalAlignment`
column
    - `tableColumnWidth` (also should be on every cell or just in the first in column - might be hard if column is spanned on top)
- Model for `tableRow`
    - `tableRowHeight`
- Model for `table`
    - `tableBorderWidth`, `tableBorderColor`, `tableBorderStyle`
    - `tableBackgroundColor`
    - `tableWidth`
    - `tableHeight`

**Comment by Reinmar** [comment]
> Model for `tableRow`
> * `tableRowHeigh`

I think this is still a table cell's setting. As the spec says:

> For each cell in col/row apply these styles

---

BTW, I did you skip the alignment (of a table, but also a horizontal alignment of a table cell) on purpose when listing those attributes?

**Comment by jodator** [comment]
I've might just miss them. The other thing is that at least MS Word places the alignment on paragraphs so this works out of the box and I wonder what we should do there.

**Comment by jodator** [comment]
OK I see that prefixing those attributes doesn't make any sense - we have `width` on `Image` element already and table has `headingRows` not `tableHadingRows`.

**Comment by jodator** [comment]
OK guys, to sum up current work status I've concluded this list to track progress to finish MVP in a step 1 form - retention of as much pasted content as possible without adding table styles support in Paste From Office. I've extracted this from [@Reinmar's comment](https://github.com/ckeditor/ckeditor5/issues/3287#issuecomment-532229447) with only relevant parts.

1. Current ticket (MVP step 1) - current state
    - [ ]  Check pasting content vs current model → (generate more follow ups if needed)
    - [ ]  Check CKEditor 4 migration
    - Generic styles conversion with styles normalization - review idea/implementation
        - [x]  Normalizing different shorthand values: `border` vs `border-left` vs `border-left-style` to single normalized object (`border` - `table[border] = { left: {style,width,color}, top, ... }` )
        - [x]  Upcasting (parsing styles) - called *"normalization"* done on `view/Element` level - existing methods)
        - [x]  Reading normalized styles properties (done on `view/Element` level - new method) using *"extracting"* process to read from complex structures (`border` for now). You can read `border-color` object from border object.
        - [x]  Downcasting (done the same way as upcasting - model is setting style properties on a `view/Element` - different features might set similar properties and the output will always be normalized (string value) in a repeatable and predictable way in a process called *"reducing"* (or *"inlining"*).
        - [ ]  Review `ViewConsumable` support for handling style shorthands (also make it pluggable as below)
        - [x]  50/50 In the future: add checking if all 4 borders are identical and then output `border`, or if all 4 colors are identical and then output `border-color`. **Note**: already done for `padding` and `margin` should be fairly easy to add it for `border` though.
        - [ ]  Make it pluggable - right now it is a singleton inside a module :/ but is done as separate "plugins" for `border`, `background` , `margin` and `padding`
        - [x]  Check above against current features that might use style property shorthand (tests should be green 100% across all codebase)
            - [x]  `Indent` - yay 1 converter less
            - [x]  `Font` - also works
    - Plugins to have:
        - [x]  `TableCellProperties`
        - [x]  `TableColumnRowProperties` handles table cell height / width
        - [x]  `TableProperties`
    - Styling (one field value + unit, adding unit automatically)
        - table cell
            - [x]  background color (as `backgroundColor`)
            - [x]  border (color, style, width) as `borderColor`, `borderSyle`, `borderWidth`
            - [ ]  width/height as `width`,  `height`
            - [x]  vertical text alignment as `verticalAlignment`
            - [ ]  horizontal text alignment as ...
            - [x]  padding as `padding`
        - table
            - [x]  background color as `backgroundColor`
            - [ ]  width/height (may need to be downcasted to `<figure>`) as `width`, `height`
            - [ ]  summary
            - [ ]  alignment (may need to be downcasted to `<figure>`)
        - [ ]  Style editing - right now it is "undefined" so styles are not copied.
2. Create follow-ups
    - [ ]  general MVP step 2 ticket (mostly UI) + Future steps
    - [ ]  add more test cases for different styles options

ps.: this comment might be updated with more steps but ATM I think that's all what's needed for MVP step 1.

**Comment by sbilgil** [comment]
when this can be on prod?

**Comment by Reinmar** [comment]
> when this can be on prod?

In two weeks 🤞

**Comment by sai-velamuri** [comment]
A big thanks for the CKEditor team. One small suggestion about the documentation is, only experienced developers can get sense out of it. A beginner will have a hard time understanding and gluing things together.

**Comment by mrleblanc101** [comment]
Referencing this here, but we lost the ability to control if the text in cell should wrap or not:
https://github.com/ckeditor/ckeditor5/issues/18932
