### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#3531]
This is an umbrella ticket for the selection. It groups all other selection tickets which are:
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/315 Selection research
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/308 Selection representation in the view.
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/163 Quirks and boguses
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/311 Selection rendering
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/310 SelectionObserver
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/312 Writer should wrap position
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/313 Model to View Selection conversion
