### ISSUE TITLE
Stabilize the API

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5#3709]
To stabilize the engine API we have a bunch of tickets waiting to be closed:
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/76 Getters should be changed to methods. 
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/156  Stop using "attr" in property names
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/165 Tree view and tree model APIs should be simmilar
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/253 Rename TreeView.TreeView to the TreeView.Document
- [x] https://github.com/ckeditor/ckeditor5-engine/issues/254 Rename `TreeView` to `View` and `TreeModel` to `Model`.
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/263 TreeView class improvements.
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/321 Model: Rename TextProxy.commonParent to .parent
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/339 Rename Batch.doc to Batch.document 
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/351 Model: ModelElement.getChildren().
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/355 Implement useful range constructors
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/363 Merge model document.composer with document.
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/364 Rename or merge view.writer.
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/370 Find better name for doc.enqueueueueueueChanges
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/375 Resolve circular dependencies
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/372 Set priority in AttributeElement constructor
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/390 Default root name 
- [ ] https://github.com/ckeditor/ckeditor5-engine/issues/383 View: Use event namespaces for the change event
