### ISSUE TITLE
Followup for the big UI library refactoring

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5269]
Follow-up for https://github.com/ckeditor/ckeditor5-ui/issues/95.

# ckeditor5-ui

- [x]  `View#addChild` -> `View#addChildren` and can't the param be an iterable? It's not consistent with e.g. `engine.view.Element#insertChildren()` and look bad here: https://github.com/ckeditor/ckeditor5-link/pull/58/files#diff-55321c76ff0d0fac681dcdaa3f17de75R60. (fixed by https://github.com/ckeditor/ckeditor5-ui/issues/108)
- [ ] `View#bindTemplate` requires some example. Or, in fact, there should be a more rich example (with bindings) in the class.
   - [ ]  In fact... why isn't this method called `bind` or `binder` or sth? I'd try to find a better name for it cause the current one confused even me.
- [ ]  I don't like that you bind an event using `domEventName: bind.to( 'viewEventName' )`. It's the opposite direction than data binding, so a separate function for that would be more clear (`bind.fire()`?... but then `bind` isn't the best word too). WDYT? Actually, maybe this deserves a bigger ticket because I also have a problem with reading `bind.if()`. Maybe someone will have a better idea for this API.

# ckeditor5-ui-default

- [x] General thing – merge multiple `this.set()` calls into one big `this.set( { keys } )`.
- [x] `EditorUI` should be brought back (closed in https://github.com/ckeditor/ckeditor5-ui-default/issues/119)
   - [x]  It should IMO contain the component factory instance (which is now in EditorUIView) and contain the code needed to bootstrap the specific UI's view (if there's any special logic).
   - [x]  I think that that we'll know what to put in the controller by checking what needs to know about the editor. Currently, the view requires it but if we move it outside then you see that:
     * editor is needed for the feature components factory,
     * initializing the toolbar requires the editor (cause the buttons are in the config and feature components in the controller).

    So, we need to decide whether it's good that a view knows about the editor. If not (and I think so, though the reason is purely theoretical – it's the view's reusability) then `EditorUI` is needed. If not, then `EditorUI` may still be needed... :D.

   * Note: I'm unsure whether we need any base class for `EditorUI`. Perhaps it's enough to define an interface in the `core` (not `ui-default`!). This will allow easily documenting in the core what `editor.ui` is supposed to contain.
   * Related issue: https://github.com/ckeditor/ckeditor5-ui/issues/77.
   * If it won't be brought back, then at least the comment in `ComponentFactory` must be fixed.

(all below fixed by https://github.com/ckeditor/ckeditor5-ui-default/issues/118)

1. `ButtonView`
   - [x] Not related to this PR, but why is native `click` prevented only when button is not enabled?
1. `EditorUIView`
   - [x] Why is `#icons` observable?
   - [x] Remove `#editor` (after bringing back `EditorUI`).
1. `EditableUIView`
   - [x] Why is `#name` defined here and not used (it's used in a child view only)?
1. `IconManagerView`
   - [x] Why is `#sprite` observable?
1. `StickyToolbarView`
   - [x] Shouldn't `destroy()` return a promise?
1. Handlers
   - [x] They should be simplified. As we discussed already – constantly adding and removing listeners just make them more fragile and requires more code.

# editor-classic

- [x] Will require changes once `EditorUI` is brought back. `ClassicEditorUIView` shouldn't know about the editor. (closed in https://github.com/ckeditor/ckeditor5-editor-classic/issues/38)

# basic-styles

- [x] https://github.com/ckeditor/ckeditor5-basic-styles/pull/32/files#diff-e1ae04aa196b2e58d217887d5c184135R40 and https://github.com/ckeditor/ckeditor5-basic-styles/pull/32/files#diff-a1955eb538778e28166800d49a7bbd88R40 – `isOn` and `isEnabled` aren't needed here cause they are set below.

(fixed by https://github.com/ckeditor/ckeditor5-basic-styles/issues/35)

# heading

- [x] https://github.com/ckeditor/ckeditor5-heading/pull/42/files#diff-dd7f09251ed58d70ff2596aaaa063701R49 – `isOn` and `isEnabled` aren't needed (cause they equal their defaults).

(fixed by https://github.com/ckeditor/ckeditor5-heading/issues/48)

# undo

- [x] https://github.com/ckeditor/ckeditor5-undo/pull/46/files#diff-0af576b118e4e50973341c83f7ecd7f9R161 – not necessary cause equals the default. 

(fixed by https://github.com/ckeditor/ckeditor5-undo/issues/49)

# link

1. `LinkFormView`
   - [x] Documentation of `cancel` and `unlink` events is missing.
   - [x] https://github.com/ckeditor/ckeditor5-link/pull/58/files#diff-55321c76ff0d0fac681dcdaa3f17de75R141 can't we delegate this?
   - [x] Why are we using a form finally?

(fixed by https://github.com/ckeditor/ckeditor5-link/issues/63)
