### ISSUE TITLE
[Umbrella] UI improvements

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5419]
# Priorities

Big things:

* [x] Drop SASS **[2+5+2=9MD]**
	* [ ] `z-index` management **[part of dropping SASS]**
	* [x] Rise specificity of CSS rules **[part of dropping SASS]**
* [x] Add `View#render()`, get rid of `View#element`'s getter **[4MD]**
* [ ] Review feature split **[5MD]**
	* [ ] Split CT plugin **[2MD]**
	* [x] Review upload package **[2MD]**
* [x] Limit inheritance **[3MD]**

Minor things:

* [x] `tag` vs `element` vs `name` **[1MD]**
* [ ] ~~Get rid of the Model class **[0MD]**~~
* [x] Rename `ContextualToolbar` -> `BalloonToolbar` **[0MD]**
* [x] `ck-` vs `cke-` **[0MD]**

Unclear priority:

* [ ] Link insertion and editing improvements **[?MD]** **[priority?]**
* [ ] Shadow DOM and custom elements support **[?MD]** **[priority?]**
* [ ] Toolbar is jittering when scrolling **[?MD]**
* [ ] Heading buttons in the toolbar **[1MD]** **[priority?]**
* [ ] Linking images **[?MD]** **[priority?]**
* [ ] Inline editors on other than `<div>` elements  **[?MD]** **[priority?]**

# Issues

## Get rid of the Model class **[0MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-ui/issues/314

Notes:

* Quick and small.
* Non-blocking.

## Split CT plugin **[2MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-ui/issues/274

Notes:

* Non-blocking.
* Will allow removing this hack: https://github.com/ckeditor/ckeditor5-editor-balloon/blob/777449f971f11e961105027b69f9358c77fdb77b/src/balloontoolbareditor.js#L35-L36

## Add `View#render()`, get rid of `View#element`'s getter **[4MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-ui/issues/262

Notes:

* Big API change.
* Blocking for docs.
* Leads to a significant simplification.

## `z-index` management **[part of dropping SASS]**

Tickets:

* https://github.com/ckeditor/ckeditor5-ui/issues/218

Notes:

* Quick and small.
* Non-blocking.

## Review feature split **[5MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5/issues/488

Notes:

* Big, breaking.
* Non-blocking (except for the headless editor which is often required).
* Still requires some research.

## Shadow DOM and custom elements support **[?MD]** **[priority?]**

Tickets:

https://github.com/ckeditor/ckeditor5-engine/issues/692

Notes:

* Still needs to be researched.
* May require big refactoring.
* Must be researched.

## Toolbar is jittering when scrolling **[?MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-editor-inline/issues/22

Notes:

* `position:sticky` plus a gracefull fallback for IE11.
* Or some other solution – must be researched.
* Local, non-block.

## Rise specificity of CSS rules **[part of dropping SASS]**

Tickets:

* https://github.com/ckeditor/ckeditor5/issues/494

Notes:

* Non-blocking.
* Completely breaking for anything outside.

## Rename `ContextualToolbar` -> `BalloonToolbar` **[0MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5/issues/550

Notes:

* Simply needs to be done.

## Heading buttons in the toolbar **[1MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5/issues/455
* https://github.com/ckeditor/ckeditor5-heading/issues/74

Notes:

* May change the builds (if we'll go with the buttons instead of the dropdown).
* Non-blocking.
* Requires "Feature split".

## Limit inheritance **[3MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5/issues/327

Notes:

* Still requires some design.
* Breaking.
* Non-blocking.
* Block docs.

## Drop SASS **[2+5+2=9MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5/issues/420
* https://github.com/ckeditor/ckeditor5-ui/issues/144

Notes:

* Needs research.
* Blocks https://github.com/ckeditor/ckeditor5-ui/issues/144 (because it's hard to predict now what's the best way for it).
* Blocks docs.
* Absolutely breaking.
* Lots of docs to update.
* Will include "Rise of specifity" and "z-index management".

## `ck-` vs `cke-` **[0MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-ui/issues/112

Notes:

* Minor cleanup.

## `tag` vs `element` vs `name` **[1MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-ui/issues/78

Notes:

* Minor cleanup.

## Link insertion and editing improvements **[?MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-link/issues/11 and https://github.com/ckeditor/ckeditor5-link/issues/73 – typing over a link (and after a link) **[10+2MD]**
* https://github.com/ckeditor/ckeditor5-link/issues/17 and https://github.com/ckeditor/ckeditor5-link/issues/31 – a way to open a link and UI simplification **[discussion+open+simplification=2+3+1MD]**
* https://github.com/ckeditor/ckeditor5-link/issues/14 – autolinking **[1-5MD]**
* https://github.com/ckeditor/ckeditor5-link/issues/13 – fake visual selection  **[2MD]**

## Review upload package **[2MD]**

Tickets:

* https://github.com/ckeditor/ckeditor5-upload/issues/22

Notes:

* Breaking.
* To be done as quickly as possible.
* Requires "Feature split".

## Linking images **[?MD]** **[priority?]**

Tickets:

* https://github.com/ckeditor/ckeditor5-link/issues/85

Notes:

* Feature.
* It may be confusing that it's not available now.
* Will validate reusability of the link feature.

## Inline editors on other than `<div>` elements

Tickets:

* https://github.com/ckeditor/ckeditor5-editor-inline/issues/5
