### ISSUE TITLE
[Umbrella] Android issues

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#614]
We'd like to sum up all problems related to `Android` compatibility, so this umbrella ticket will contain all known issues.

**Typing**:
* [x] <kbd>Backspace</kbd> on the line beginning - https://github.com/ckeditor/ckeditor5/issues/1106.
* [x] Typing over / removing an image - https://github.com/ckeditor/ckeditor5-typing/issues/161.
* [ ] Cannot remove last character inside block element - https://github.com/ckeditor/ckeditor5/issues/1080.
* [x] Word duplicates after pressing <kbd>Enter</kbd> - https://github.com/ckeditor/ckeditor5-enter/issues/47.
* [x] <kbd>Enter</kbd> issues after turning device off and on - https://github.com/ckeditor/ckeditor5-enter/issues/48.
* [ ] Incorrect content removal with <kbd>Backspace</kbd> - #1127 
* [x] Typing over non-collpased, non-flat selection issue - #1130
* [ ] Misplaced selection after removing image - https://github.com/ckeditor/ckeditor5-typing/issues/166

**Autocorrect**:
* [ ] Autocorrect inline styles issue - https://github.com/ckeditor/ckeditor5-typing/issues/159.
* [ ] Autocorrect inline styles on the line end issue - https://github.com/ckeditor/ckeditor5-typing/issues/160.

**UX**:
* [x] Zooming on focus for certain elements - https://github.com/ckeditor/ckeditor5/issues/1070.
* [x] Balloon toolbar hides under native controls - https://github.com/ckeditor/ckeditor5/issues/1107.

**WebView related**:
* [x] Backspace doesn't work properly - https://github.com/ckeditor/ckeditor5/issues/613.
* [x] Creating editor inside WebView - https://github.com/ckeditor/ckeditor5/issues/683, https://github.com/ckeditor/ckeditor5/issues/1000.
* [x] Typing inside editor in a WebView - https://github.com/ckeditor/ckeditor5/issues/701.

**Comment by szymonkups** [comment]
Some conclusions for now after working for a while with Android Chrome`63.0.3239.11`:
- there is no `beforeinput` event fired when deleting content,
- there is `input` event when deleting content, but:
    - it is always fired with `inputType: deleteContentBackward`, no matter if it is deleting a letter, word, line of text or block. Specs [1] say that it should be fired only on non-collapsed selection but it is fired also when deleting letter by letter with collapsed selection,
    - `event.getTargetRanges` always returns an empty array, so together with only `deleteContentBackward` event fired there is no distinction if single letter was deleted, word, or larger content,
    - couple of `selectionchange` events are fired after the event. If we would manage somehow to handle `input` event correctly, we would need to block `selectionchange` for a while (because now they will contain outdated information),
    - `input` type event cannot be prevented so we cannot do much more.

In that situation we decided to stay with mutation-handling-approach. 
[1] https://www.w3.org/TR/input-events-1/

**Comment by Reinmar** [comment]
WIP:

* https://github.com/ckeditor/ckeditor5-typing/tree/t/ckeditor5/613-mutations
* https://github.com/ckeditor/ckeditor5-typing/tree/t/ckeditor5/613

**Comment by f1ames** [comment]
I have updated initial comment adding other Android related issues which were reported in the meantime.

**Comment by f1ames** [comment]
After some debugging/testing I have reached the same conclusions as @szymonkups in `t/ckeditor5/613-mutations`. We could recognise if mutations array contains mutation which shows container element removal and base on that proceed accordingly (executing `delete` command basically).

However, there is a problem with non-collapsed selection (containing more than one block element). It seems that there is some race condition / unstable behaviour when it comes to selection. For example imagine selection like:

```
<h1>[Header 1</h1>
<p>Paragraph]</p>
```

Then <kbd>Backspace</kbd> is pressed. In most cases, in `Input` plugin (inside `keydown` and `mutations` handler), model has a selection like `<h1>Header 1</h1><p>Paragraph[]</p>`. Sometimes there is selection like `<h1>[Header 1</h1><p>Paragraph]</p>`, but it seems quite random. I haven't found any difference between those two situations yet.

**Comment by Reinmar** [comment]
Pity. We can store the previous selection (e.g. from 10ms before the action) and use it there.

BTW, I think that it'd be good to place all these new handled in a new plugin. Like `InputMobile` or `InputOnscreenKeyboard`. `Input` gets crowded, so we can split the code. In fact, this will help to disable this entire plugin if a non-mobile environment was detected.

**Comment by f1ames** [comment]
> Pity. We can store the previous selection (e.g. from 10ms before the action) and use it there.

I'm checking what are possible options here and if it is a native issue or is it caused by our code.

> BTW, I think that it'd be good to place all these new handled in a new plugin. Like InputMobile or InputOnscreenKeyboard. Input gets crowded, so we can split the code. In fact, this will help to disable this entire plugin if a non-mobile environment was detected.

Makes sense 👍.

**Comment by f1ames** [comment]
Ok, I did some tests how non-collapsed selection behaves when removing its content on Android and desktop Chrome with https://codepen.io/f1ames/pen/yERbMe?editors=1010.

The initial HTML is:

```
<h2>[Header 1</h2>
<p>Paragraph]</p>
```

And then <kbd>Backspace</kbd> is pressed.

**Desktop** (event name - DOM and selection):

1. `keydown` - `<h2>[Header 1</h2><p>Paragraph]</p>`
1. `mutations` - `<h2>[]</h2>`
1. `selectionchange` - `<h2>[]</h2>`

**Android** (event name - DOM and selection):

1. `selectionchange` - `<h2>Header 1</h2><p>Paragraph[]</p>`
1. `keydown` - `<h2>Header 1</h2><p>Paragraph[]</p>`
1. `mutations` - `<h2>[]</h2>`
1. `selectionchange` - `<h2>[]</h2>`

Sometimes the first `selectionchange` event is not fired at all.

---

> Pity. We can store the previous selection (e.g. from 10ms before the action) and use it there.

I think it will be reasonable to store previous selection and then check what we can do with it. However,  we cannot exactly relay on any timings here, because someone can change selection (`selectionChange` event fired), leave a device and then press <kbd>Backspace</kbd> after 5 minutes. And there is no event preceding the one with already changed selection so we cannot fetch the previous selection just before it.

What we can check is if:

* previous and current selections are different
* previous selection is non-collapsed one
* previous selection has the same end as the current one (as you may notice, on <kbd>Backspace</kbd>, the selection always gets collapsed to its end on Android)

and if previous selection meets all the above, use it to remove its content.

**Comment by f1ames** [comment]
There is one issue with undo when using previous selection to remove content. As the selection upon pressing <kbd>Backspace</kbd> is changed from `<h2>[Header 1</h2><p>Paragraph]</p>` to `<h2>Header 1</h2><p>Paragraph[]</p>` by the borwser it is reflected in an undo step. So after deleting content if undo is used, instead of going back to `<h2>[Header 1</h2><p>Paragraph]</p>` it restores `<h2>Header 1</h2><p>Paragraph[]</p>` state.

**Comment by jodator** [comment]
Might be another one: https://github.com/ckeditor/ckeditor5/issues/1786.

**Comment by CKEditorBot** [comment]
There has been no activity on this issue for the past year. We've marked it as stale and will close it in 30 days. We understand it may be relevant, so if you're interested in the solution, leave a comment or reaction under this issue.

**Comment by CKEditorBot** [comment]
We've closed your issue due to inactivity over the last year. We understand that the issue may still be relevant. If so, feel free to open a new one (and link this issue to it).
