### ISSUE TITLE
[Umbrella] Feature cleanup

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#622]
* [x]  https://github.com/ckeditor/ckeditor5/issues/488 Review feature split into engine and UI parts
* [ ] https://github.com/ckeditor/ckeditor5/issues/425 Dependency injection (late binding)
* [x] https://github.com/ckeditor/ckeditor5-upload/issues/22 Review ckeditor5-upload's content
* [x] https://github.com/ckeditor/ckeditor5/issues/550 Rename ctxToolbar to balloonToolbar
* [ ] https://github.com/ckeditor/ckeditor5-ui/issues/274 Split balloonToolbar to a component and a plugin

**Comment by Reinmar** [comment]
Most of these issues were done already and I'm not sure when we'll do the rest, so I'm closing this umbrella.
