### ISSUE TITLE
Table cell/row/column selection – stage III (optional features)

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6297]
This is a followup for the table selection optional features (after stage II: #6285).

- [x] #6120: Pasting table into a selected table fragment (bigger than one cell)
    - [x] #6769: Handle case of a smaller table pasted into bigger selection
- [x] #6121: Pasting table when only one table cell is selected
- [x] #6122: Handling spanned cell in pasting scenarios
- [x] #6115: Table selection with keyboard
- [x] #6453: Multiselection breaks in tables while holding Shift key
- [x] #6446: The live preview of the table cell background should work with multiple-cell selection
- [x] #6631: The arrow next to the "merge cells" button seems to be disabled
