### ISSUE TITLE
Migration to monorepo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6466]
We've been using multirepo for quite some time now, but as the time goes by we see that it is being less and less productive for our use case.

*   Working with the code will be simpler (now we use home made `mrgit` tool to do that comfortably)
*   Release tools are much more complicated with multirepo, more synchronization needed.
*   Many times it requires additional software (e.g. TravisCI - making PRs in multiple packages to fix one issue requires you to checkout this PR related branch for every dependency, otherwise it fails the tests)

There are multiple things to be handled in this project (along with the priority):

*   [x] [Merge CKEditor 5 subrepositories to the main repository (p1)](https://github.com/ckeditor/ckeditor5/issues/6476)
*   [x] [Update CI (p2,p3?)](https://github.com/ckeditor/ckeditor5/issues/6477)
*   [x] [Code coverage (p3)](https://github.com/ckeditor/ckeditor5/issues/6478)
*   [x] Adjust dev tools
    *   [x] [Testing (p1)](https://github.com/ckeditor/ckeditor5-dev/issues/605)
*   [x] [Online builder - we need to make sure works well (p2)](https://github.com/ckeditor/ckeditor5/issues/6480)

### Stage 2

*    [x] [Deploy changes to the CKEditor 5 repository](https://github.com/ckeditor/ckeditor5/issues/6534)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Added [`monorepo-mock`](https://github.com/ckeditor/ckeditor5/tree/monorepo-mock) branch, that has the file layout that we should be looking for, we can use it for further testing.

**Comment by mlewand** [comment]
All right we migrated repositories:

![](https://user-images.githubusercontent.com/5353898/80840006-aa18e880-8bfc-11ea-9d5a-50a7702a1762.png)

There's still some documentation to be updated - this will be handled at the beginning on of upcoming week.

**Comment by mlewand** [comment]
Moved followups to stage II #6746.

**Comment by robclancy** [comment]
I'm so glad you changed your mind on this (https://github.com/ckeditor/ckeditor5/issues/6014). I have had to search so much to find things.
