### ISSUE TITLE
Monorepo migration stage II

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#6746]
## Provide a description of the task

In #6466 we migrated all our CKEditor 5 packages to a single github repository.

When doing that we identified a few remaining tasks, that should be grouped in a separate epic task.

*   [x] [Docs](https://github.com/ckeditor/ckeditor5/issues/6479)
*   [x] Remaining ckeditor5-dev changes:
    *   [x] [Releasing](https://github.com/ckeditor/ckeditor5-dev/issues/606)
    *   [x] [Changelog generation](https://github.com/ckeditor/ckeditor5-dev/issues/608)

And a few minor cleanups.
