### ISSUE TITLE
Migrate to beforeInput

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#7462]
## 📝 Provide a description of the improvement

AFAICT https://bugzilla.mozilla.org/show_bug.cgi?id=970802 and https://bugzilla.mozilla.org/show_bug.cgi?id=1449831 landed in Firefox 76. That means that we can replace the current mutation-based typing handling with `beforeInput` 🎉.

It'd probably be good to keep the mutation handler for environments that do not support `beforeInput` yet, even if we don't officially support them (probably older versions of FF or Safari). On all environments that support `beforeInput` we should use it, though.

The goal is to use `beforeInput` to handle:

*   typing (all types of it, including IME and autocorrect)
*   spellchecking
*   enter
*   delete

As next steps we can also consider using it as an additional trigger for:

*   inline formatting: bold, italic, etc.,
*   and perhaps more

Some additional issues that might get fixed with it:

*   #7903 - Crash when undoing typing (model-nodelist-offset-out-of-bounds)
*   #8052 - Exception thrown when undoing link with a non-collapsed selection

---

*   [x] #7995 – Implement the `beforeInput` support detection
*   [x] #7996 – Improve InputObserver so the event passes and normalizes additional information
*   [x] #7997 – Migrate the Input plugin to the `beforeInput` event
*   [x] #7998 – Migrate the Delete plugin to the `beforeInput` event
*   [x] #7999 – Migrate the Enter and ShiftEnter plugins to `beforeInput`
*   [ ] #8000 – Use format\* `beforeInput` types across the features
*   [ ] #8001 – Use insert\* `beforeInput` types across the features (list, horizontal line, etc.)
*   [ ] #8008 – Test and stabilize composition (IME) using beforeInput on desktop browsers (Mac)
*   [ ] #8009 – Test and stabilize composition (IME) using beforeInput on desktop browsers (Windows)
*   [ ] #8010 – Test and stabilize composition (IME) using beforeInput on desktop browsers (Linux)
*   [ ] #8011 – Test and stabilize composition (IME) using beforeInput on Android
*   [ ] #8012 – Test and stabilize composition (IME) using beforeInput on iOS
*   [ ] #8013 – Test and stabilize beforeInput in Cloud Features

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by oleq** [comment]
Order of things:
1. In the beginning, we're merging into a feature branch.
2. Then we merge the feature branch to master but the feature is disabled by default (see #7995).
3. Then we merge issues to master.
4. Then we pray.

**Comment by liuda101** [comment]
hi, any progress here?

**Comment by KevinWang15** [comment]
+1 for this, Chinese IME support is really of critical importance to my project
See #10219 #10284

**Comment by keng0o** [comment]
hi, any progress here?

**Comment by keng0o** [comment]
The same problem is occurring in Japanese.
What is the current situation?

**Comment by Reinmar** [comment]
There's been a lot of work put in this ticket in the past, but then we had to stop for about 1 year. 

**The good news is that we restarted the work** :tada: **.** However, we continue in a new ticket to have a clearer picture of where we are because a lot of things happened in the meantime.

The new ticket is #11438 and I'm closing this one.
