### ISSUE TITLE
Review the status of the list styles feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#8026]
1. Tests.
2. Pick important issues.

**Comment by pomek** [comment]
- [ ] Creating a numbered list above an unordered list results with a unordered #7932
- [ ] Wrong list style in undo stack after merging two different list styles #7930
- [ ] The listStyle attribute for listItem should be marked as `isFormatting` #7894

**Comment by FilipTokarski** [comment]
Very recent regression - https://github.com/ckeditor/ckeditor5/issues/8072

**Comment by FilipTokarski** [comment]
Another one - https://github.com/ckeditor/ckeditor5/issues/8073

**Comment by pomek** [comment]
Weird case with using the same list style in nested lists: https://github.com/ckeditor/ckeditor5/issues/8081

Maybe it's somehow connected with https://github.com/ckeditor/ckeditor5/issues/7930.

**Comment by pomek** [comment]
Blocked bugs have been fixed. Pasting from and Exporting to Word I reported to separate issues (https://github.com/ckeditor/ckeditor5/issues/8104, https://github.com/ckeditor/ckeditor5/issues/8103).
